import styles from "../styles/About.module.css";
import Head from "next/head";
import img from "../public/vercel.svg";

function about() {
    return (
        <>
        <Head>
            <title>Acerca de</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>
            <div className={styles.containerText}>
                <h1>Aplicación creada para para adquirir mas conocimientos con Nextjs</h1>
            </div> 
        </div>
    </>
    )
}

export default about;
