import styles from "../styles/About.module.css";
import Link from "next/link";
import  Head  from "next/head";

export default function about() {
    return (
    <>
        <Head>
            <title>About page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>
            <h1>cariniooo</h1>
            <Link href="/" >regresar</Link>
        </div>
    </>
    )
}
