import styles from "../styles/CriptoInfo.module.css";
import  Head  from "next/head";

export default function about() {
    return (
    <>
        <Head>
            <title>Cripto Info</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.container}>
            <div className={styles.containerText}>
                <h1>¿Qué son las Criptomonedas?</h1>
                <p>
                    Una criptomoneda es algo similar a un dinero digital. 
                    Con el cual podrás pagar a tus amigos tu parte del bar, comprar ese par de medias que vistes 👀, reservar vuelos ✈️ y hoteles 🏨 para tus próximas vacaciones.
                    Como las criptomonedas son digitales, es posible que puedas transferírselas a tus amigos y familiares sin importar en que parte del mundo se encuentren.
                </p>
            </div> 
        </div>
    </>
    )
}
